import "@/styles/globals.css"
import { PageProvider } from "@/context/page-context"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PageProvider>{children}</PageProvider>
      </body>
    </html>
  )
}
